apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws_jenkins_1_argo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: aws_jenkins_1_argo
  template:
    metadata:
      labels:
        app: aws_jenkins_1_argo
    spec:
      containers:
      - name: aws_jenkins_1_argo
        image: hanoguz00/github_aws_1:1.0.49
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
